// Adaptive AUTOSAR C++ Application (AA)
// Receives inference result from ROS2 via ARA::Com and generates control commands

#include <memory>
#include <iostream>
#include "ara/core/future.h"
#include "ara/com/com_error_domain.h"
#include "ara/com/someip_binding/someip_proxy.h"
#include "inference_service_proxy.h"  // Auto-generated by AUTOSAR tooling
#include "vehicle_control_publisher.h" // Hypothetical control interface

class InferenceAAApplication {
public:
    InferenceAAApplication()
        : inferenceProxy(std::make_shared<InferenceServiceProxy>()) {}

    void Init() {
        // Subscribe to the inference result from ROS2
        auto future = inferenceProxy->Subscribe();

        // Register callback when inference data is received
        inferenceProxy->GetResultField().Subscribe([this](const InferenceResult& result) {
            this->OnInferenceReceived(result);
        });
    }

private:
    std::shared_ptr<InferenceServiceProxy> inferenceProxy;

    void OnInferenceReceived(const InferenceResult& result) {
        float steering = result.steering;
        float throttle = result.throttle;

        std::cout << "[AA] Received Inference: Steering=" << steering << ", Throttle=" << throttle << std::endl;

        // Generate vehicle control command
        VehicleControl cmd;
        cmd.steering_angle = steering;
        cmd.speed = throttle;

        // Publish control to vehicle interface (ROS2 or hardware interface)
        VehicleControlPublisher::Publish(cmd);
    }
};

int main() {
    InferenceAAApplication app;
    app.Init();

    // Main loop or event-driven execution handled by AUTOSAR runtime
    while (true) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    return 0;
}